name: generic

dependencies:
  - numpy
  - toolz
  - matplotlib
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - seaborn
  - jupyter
  - jupyterlab
  - ipywidgets
  - ipykernel
  - ipython

